//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountWcfV2Client.AccountService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInfo", Namespace="http://schemas.datacontract.org/2004/07/DatabaseLayer.Models")]
    [System.SerializableAttribute()]
    public partial class AccountInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string useridField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userid {
            get {
                return this.useridField;
            }
            set {
                if ((object.ReferenceEquals(this.useridField, value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountServiceFault", Namespace="http://schemas.datacontract.org/2004/07/AccountWcfV2")]
    [System.SerializableAttribute()]
    public partial class AccountServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.IAccountService")]
    public interface IAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/CreateAccount", ReplyAction="http://tempuri.org/IAccountService/CreateAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AccountWcfV2Client.AccountService.AccountServiceFault), Action="http://tempuri.org/IAccountService/CreateAccountAccountServiceFaultFault", Name="AccountServiceFault", Namespace="http://schemas.datacontract.org/2004/07/AccountWcfV2")]
        bool CreateAccount(AccountWcfV2Client.AccountService.AccountInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/CreateAccount", ReplyAction="http://tempuri.org/IAccountService/CreateAccountResponse")]
        System.Threading.Tasks.Task<bool> CreateAccountAsync(AccountWcfV2Client.AccountService.AccountInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/AuthAccount", ReplyAction="http://tempuri.org/IAccountService/AuthAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AccountWcfV2Client.AccountService.AccountServiceFault), Action="http://tempuri.org/IAccountService/AuthAccountAccountServiceFaultFault", Name="AccountServiceFault", Namespace="http://schemas.datacontract.org/2004/07/AccountWcfV2")]
        AccountWcfV2Client.AccountService.AuthAccountResponse AuthAccount(AccountWcfV2Client.AccountService.AuthAccountRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/AuthAccount", ReplyAction="http://tempuri.org/IAccountService/AuthAccountResponse")]
        System.Threading.Tasks.Task<AccountWcfV2Client.AccountService.AuthAccountResponse> AuthAccountAsync(AccountWcfV2Client.AccountService.AuthAccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthAccount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AccountWcfV2Client.AccountService.AccountInfo info;
        
        public AuthAccountRequest() {
        }
        
        public AuthAccountRequest(AccountWcfV2Client.AccountService.AccountInfo info) {
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthAccountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AuthAccountResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public AccountWcfV2Client.AccountService.AccountInfo info;
        
        public AuthAccountResponse() {
        }
        
        public AuthAccountResponse(bool AuthAccountResult, AccountWcfV2Client.AccountService.AccountInfo info) {
            this.AuthAccountResult = AuthAccountResult;
            this.info = info;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountServiceChannel : AccountWcfV2Client.AccountService.IAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<AccountWcfV2Client.AccountService.IAccountService>, AccountWcfV2Client.AccountService.IAccountService {
        
        public AccountServiceClient() {
        }
        
        public AccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateAccount(AccountWcfV2Client.AccountService.AccountInfo info) {
            return base.Channel.CreateAccount(info);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAccountAsync(AccountWcfV2Client.AccountService.AccountInfo info) {
            return base.Channel.CreateAccountAsync(info);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AccountWcfV2Client.AccountService.AuthAccountResponse AccountWcfV2Client.AccountService.IAccountService.AuthAccount(AccountWcfV2Client.AccountService.AuthAccountRequest request) {
            return base.Channel.AuthAccount(request);
        }
        
        public bool AuthAccount(ref AccountWcfV2Client.AccountService.AccountInfo info) {
            AccountWcfV2Client.AccountService.AuthAccountRequest inValue = new AccountWcfV2Client.AccountService.AuthAccountRequest();
            inValue.info = info;
            AccountWcfV2Client.AccountService.AuthAccountResponse retVal = ((AccountWcfV2Client.AccountService.IAccountService)(this)).AuthAccount(inValue);
            info = retVal.info;
            return retVal.AuthAccountResult;
        }
        
        public System.Threading.Tasks.Task<AccountWcfV2Client.AccountService.AuthAccountResponse> AuthAccountAsync(AccountWcfV2Client.AccountService.AuthAccountRequest request) {
            return base.Channel.AuthAccountAsync(request);
        }
    }
}
